version: '3'
services:
  flask:
    build:
      context: app
      dockerFile: DockerFile
    container_name: flask
    image: ///////
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
